-- Repeatable RLS checks for catalog/profiles/assignments (F-01).
-- Copy-paste blocks into Studio SQL editor (or psql) one section at a time.
-- Do not run this file with `supabase db query --file` — every statement is
-- a commented snippet so it cannot be executed as a batch.
-- Replace UUID placeholders after signing up two users.
--
-- Impersonation uses request.jwt.claims JSON (what auth.uid() reads), not
-- the legacy request.jwt.claim.sub GUC.

-- Look up users:
-- SELECT id, email FROM auth.users;

-- Promote one admin (service role / postgres; bypasses RLS):
-- UPDATE public.profiles SET role = 'admin' WHERE id = '<admin-uuid>';

-- ---------------------------------------------------------------------------
-- Seed catalog rows as postgres (bypasses RLS)
-- ---------------------------------------------------------------------------
-- INSERT INTO public.catalog_items (title, status)
-- VALUES ('Pending Book', 'pending'), ('Approved Book', 'approved')
-- ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Regular user: approved catalog only; no other users' assignments
-- ---------------------------------------------------------------------------
-- BEGIN;
-- SET LOCAL ROLE authenticated;
-- SELECT set_config(
--   'request.jwt.claims',
--   json_build_object('sub', '<user-a-uuid>', 'role', 'authenticated')::text,
--   true
-- );
-- SELECT id, title, status FROM public.catalog_items;           -- approved only
-- SELECT * FROM public.user_assignments;                        -- own rows only
-- INSERT INTO public.user_assignments (user_id, catalog_item_id, list_type)
-- VALUES (
--   '<user-a-uuid>',
--   (SELECT id FROM public.catalog_items WHERE title = 'Approved Book' LIMIT 1),
--   'library'
-- );                                                             -- should succeed
-- INSERT INTO public.user_assignments (user_id, catalog_item_id, list_type)
-- VALUES (
--   '<user-a-uuid>',
--   (SELECT id FROM public.catalog_items WHERE title = 'Pending Book' LIMIT 1),
--   'library'
-- );                                                             -- should fail
-- COMMIT;

-- ---------------------------------------------------------------------------
-- Admin: all catalog statuses; can insert/update/delete catalog items
-- ---------------------------------------------------------------------------
-- BEGIN;
-- SET LOCAL ROLE authenticated;
-- SELECT set_config(
--   'request.jwt.claims',
--   json_build_object('sub', '<admin-uuid>', 'role', 'authenticated')::text,
--   true
-- );
-- SELECT id, title, status FROM public.catalog_items;           -- pending + approved + rejected
-- INSERT INTO public.catalog_items (title, status) VALUES ('Admin Insert', 'pending');
-- COMMIT;

-- ---------------------------------------------------------------------------
-- Cross-user leak: User B must not see User A's assignments
-- ---------------------------------------------------------------------------
-- BEGIN;
-- SET LOCAL ROLE authenticated;
-- SELECT set_config(
--   'request.jwt.claims',
--   json_build_object('sub', '<user-b-uuid>', 'role', 'authenticated')::text,
--   true
-- );
-- SELECT * FROM public.user_assignments;                        -- empty or B's rows only
-- COMMIT;

-- ---------------------------------------------------------------------------
-- Role self-promotion must fail for a regular user
-- ---------------------------------------------------------------------------
-- BEGIN;
-- SET LOCAL ROLE authenticated;
-- SELECT set_config(
--   'request.jwt.claims',
--   json_build_object('sub', '<user-a-uuid>', 'role', 'authenticated')::text,
--   true
-- );
-- UPDATE public.profiles SET role = 'admin' WHERE id = '<user-a-uuid>';  -- should fail
-- COMMIT;

-- ---------------------------------------------------------------------------
-- Unauthenticated (anon): no domain rows
-- ---------------------------------------------------------------------------
-- BEGIN;
-- SET LOCAL ROLE anon;
-- SELECT * FROM public.profiles;
-- SELECT * FROM public.catalog_items;
-- SELECT * FROM public.user_assignments;
-- COMMIT;
